n_sessions: 40
master_file: ./data/master.json

seg_controls:
  segment: true
  half_life: 600
  min_duration: 60

structure:
  duration: 1800
  table_sizes: [4, 4, 4]

speaker:
  libri_index_file: ./data/libri_index.csv
  offset_scale: 4000
