audio_root: .

structure_file: ./test_data/echi_structure.json
scene_file: ./scene.json

samplerate: 16000

speaker:
  ids: [150, 3240, 5463, 6437, 5022, 1553, 32, 6078, 8425, 6367, 8629, 1355]
  offset_scale: 16000

libri_index_file: ./data/libri_index.csv
