scene_file: ./data/master.json

audio_in_root: ./data/LibriSpeech/train-clean-100
audio_out_dir: ./data/echi_audio
audio_out_filename: ./audio.wav

samplerate: 16000
target_rms: 0.05

diffuse:
  n_channels: 4
  n_speaker_babble: 20
  utterance_index: ./data/libri_index.csv
